components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: Esta API permite buscar información sobre distintos componentes que
    conforman el software de Bantotals.
  title: API de Búsqueda de Componentes de Bantotal
  version: 1.0.0
openapi: 3.0.3
paths:
  /health:
    get:
      operationId: health_check_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Health Check
  /openapi.yaml:
    get:
      description: Retorna la especificación OpenAPI en formato YAML.
      operationId: get_openapi_yaml_openapi_yaml_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Obtener especificación OpenAPI en YAML
  /tablas/buscar_atributo:
    get:
      description: Busca un atributo específico en el archivo JSON. Puede filtrar
        por tabla.
      operationId: search_by_attribute_tablas_buscar_atributo_get
      parameters:
      - description: String a buscar dentro de los códigos de los atributos
        in: query
        name: query
        required: true
        schema:
          description: String a buscar dentro de los códigos de los atributos
          title: Query
          type: string
      - description: Opcional. Filtra los resultados de búsqueda solo para la tabla
          especificada
        in: query
        name: table_filter
        required: false
        schema:
          default: ''
          description: Opcional. Filtra los resultados de búsqueda solo para la tabla
            especificada
          title: Table Filter
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Buscar por Atributo
  /tablas/buscar_tablas:
    get:
      description: Busca una tabla específica en el archivo JSON.
      operationId: search_by_table_tablas_buscar_tablas_get
      parameters:
      - description: String a buscar dentro de los nombres de las tablas
        in: query
        name: query
        required: true
        schema:
          description: String a buscar dentro de los nombres de las tablas
          title: Query
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Buscar por Tabla
servers:
- description: Servidor local
  url: https://127.0.0.1:8000
- description: Servidor de producción
  url: https://mi-servidor-produccion.com
